---
version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /client
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: tuesday
    groups:
      all:
        patterns:
          - "*"
